#!/bin/bash

if [ ! -e contract.address.txt ]
then
    echo "contract does not exist"
    exit	
fi

CONTRACT_ADDRESS=$(cat contract.address.txt)

echo "adding dircetory to contract: $CONTRACT_ADDRESS"

./checksum.sh -ad $CONTRACT_ADDRESS $@ -algorithm SHA-256

